version: '3.8'
services:
  bot:
    build:
      dockerfile: Dockerfile
    container_name: insight-bot
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./:/node_modules
      - ./:/authContainer
      - ./:/.wwebjs_cache